# Deployment
pods:
  image: yanivomc/spring-music
  tag: latest
  replica: 2

database:
  dbname: db_mysql
  dbtable: music

service:
  type: ClusterIP
  port: 80       
  targetPort: 8000 
  name: http

env:
  type: "LOCAL"
  APP_PORT: "8000"
