name: marketplace-hello-world

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World JS Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "GitHub Actions Student"
