name: trivy-scan

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:
    inputs:
      severity_level:
        description: 'Choose scan severity level'
        required: true
        default: 'HIGH,CRITICAL'
        type: choice
        options:
          - 'CRITICAL'
          - 'HIGH,CRITICAL'
          - 'LOW,MEDIUM,HIGH,CRITICAL'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: '1'
          severity: '${{ inputs.severity_level }}'
          # שימוש בבופר/מטמון של Trivy (dependency cache)
          cache: true
